### ISSUE TITLE
Not in F-Droid

### ISSUE THREAD

**Issue by mirabilos** [ascendedguard/android-kanji-fix#8]
I cannot find this application at: https://f-droid.org/repository/browse/?fdfilter=Kanji&fdpage=1&page_id=0

**Comment by mirabilos** [comment]
Excuse me @ascendedguard  but why did you close this?

**Comment by ascendedguard** [comment]
I don't have a problem with someone else posting it on that site, but I'll
only be distributing on GitHub and the Play Store.
